name: keyring_web
version: 1.0.0
description: In-memory keyring store for testing and non-native environments
homepage: https://github.com/kingwill101/keyring
repository: https://github.com/kingwill101/keyring
issue_tracker: https://github.com/kingwill101/keyring/issues
topics:
  - keyring
  - credentials
  - testing
  - in-memory

resolution: workspace
environment:
  sdk: ^3.12.1

dependencies:
  keyring_core: any
  crypto: ^3.0.3

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
