name: keyring_web
version: 1.0.0
description: Web keyring implementation using IndexedDB and Web Crypto

resolution: workspace
environment:
  sdk: ^3.12.1

dependencies:
  keyring_core: any
  crypto: ^3.0.3

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
